@startuml

title First Page
Alice -> Bob : message 1
Alice -> Bob : message 2
newpage Seecond Page
Alice -> Bob : message 3
Alice -> Bob : message 4
newpage Last Page
Alice -> Bob : message 5
Alice -> Bob : message 6



@enduml