@startuml

left to right direction

:商家:
商家 --> (注册)
商家 --> (登录)
商家 --> (修改个人信息)
商家 --> (添加商品)
商家 --> (修改商品)
商家 --> (删除商品)
商家 --> (查看订单)
商家 --> (查看顾客评价)

添加商品 <.. (查询商品) : <<include>>
修改商品 <.. 查询商品 : <<include>>
删除商品 <.. 查询商品 : <<include>>


@enduml