@startuml

left to right direction

:顾客:
顾客 --> (注册)
顾客 --> (登录)
顾客 --> (修改个人信息)
顾客 --> (查询商品)
顾客 --> (查看商品详情)
顾客 --> (下单)
顾客 --> (确认收货)
顾客 --> (申请退货)
顾客 --> (评价订单)

note "aaa" as n
n .. 注册

查看商品详情 <.. (选择颜色) : <<include>>
下单 <.. (付款) : <<include>>
确认收货 <.. (查询订单) : <<include>>
申请退货 <.. (查询订单) : <<include>>

@enduml